[package]
name = "rust_telegram_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.24"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
